# -*- coding: utf-8 -*-
"""Week_3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j4M0TQoHJlFGj_jH6QPYMwVtboNW2bKg
"""

import pandas as pd

df = pd.read_excel("/content/drive/MyDrive/AAPL.xlsx")

df.head()

df.columns = df.columns.str.strip()

df.columns = df.columns.str.strip()

print("\nColumn Names:")
print(df.columns)

cols = ["Open", "High", "Low", "Close", "Volume"]

for col in cols:
    df[col] = pd.to_numeric(df[col], errors="coerce")

df = df.dropna(subset=cols)

mean_vol = df["Volume"].mean()
std_vol = df["Volume"].std()

df["Volume_Anomaly"] = (
    abs(df["Volume"] - mean_vol) > 2 * std_vol
)

mean_return = df["Daily_Return"].mean()
variance_return = df["Daily_Return"].var()
std_return = df["Daily_Return"].std()

print("\nStock Return Statistics")
print("-----------------------")
print("Mean Return:", mean_return)
print("Variance:", variance_return)
print("Standard Deviation:", std_return)

print("\nAnomalous Trading Days:")
print(
    df[df["Volume_Anomaly"]][
        ["Date", "Volume"]
    ]
)

print("\nCleaned Data:")
print(
    df[
        [
            "Date",
            "Open",
            "High",
            "Low",
            "Close",
            "Volume",
            "Price_Delta",
            "Daily_Return",
            "Volume_Anomaly"
        ]
    ].head(10)
)