# -*- coding: utf-8 -*-
"""Week_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1aHIqXVpVLuUutd-g8cH_zwDcSSHefBsH

**Shopify Stock Visualization, Time-Series Analysis & Financial Insights**
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_excel("/content/drive/MyDrive/AAPL.xlsx")

from google.colab import drive
drive.mount('/content/drive')

df.head()

df.columns

df.dtypes

df["Date"] = pd.to_datetime(df["Date"],utc=True)
df['Date'].dtype

df = df.sort_values("Date")

df["Date"] = pd.to_datetime(df["Date"],utc=True)
df

#OHLC
plt.figure(figsize=(16, 8))

plt.plot(df.index, df["Open"], label="Open")
plt.plot(df.index, df["High"], label="High")
plt.plot(df.index, df["Low"], label="Low")
plt.plot(df.index, df["Close"], label="Close")

plt.title("Shopify Stock OHLC Prices")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

plt.figure(figsize=(16,8))

plt.plot(df["Date"],df["Volume"])
plt.title("Shopify volume analysis")
plt.xlabel("Date")
plt.ylabel("Volume of trade shares")
plt.show()

df["MA20"] = df["Close"].rolling(window=20).mean()

df["MA50"] = df["Close"].rolling(window=50).mean()

plt.figure(figsize=(12, 6))

plt.plot(df.index, df["Close"], label="Daily Close")
plt.title("Shopify Stock closing price trend")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

#Moving Average
plt.figure(figsize=(12, 6))

plt.plot(df['Date'], df["MA20"], label="20-Day MA")

plt.title("Shopify Stock Price Moving Averages for short term")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

#Moving Average
plt.figure(figsize=(12, 6))

plt.plot(df['Date'], df["MA50"], label="50-Day MA")

plt.title("Shopify Stock Price Moving Averages for long term")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

#Moving Average
plt.figure(figsize=(12, 6))

plt.plot(df.index, df["Close"], label="Daily Close")
plt.plot(df.index, df["MA20"], label="20-Day MA")
plt.plot(df.index, df["MA50"], label="50-Day MA")

plt.title("Shopify Stock Price and Moving Averages")
plt.xlabel("Date")
plt.ylabel("Price")
plt.legend()
plt.xticks(rotation=45)
plt.show()

#Daily return
df["Daily_Return"] = df["Close"].pct_change()


df

plt.figure(figsize=(10, 6))

sns.histplot(
    df["Daily_Return"].dropna(),
    bins=50,
    kde=True
)

plt.title("Shopify Daily Returns")
plt.xlabel("Daily Return")
plt.ylabel("Frequency")
plt.show()

#Rolling Volatility
df["Rolling_Volatility_20"] = (
    df["Daily_Return"]
    .rolling(window=20)
    .std()
)
df["Rolling_Volatility_20"].dropna()

plt.figure(figsize=(12, 6))

plt.plot(
    df.index,
    df["Rolling_Volatility_20"]
)

plt.title("Shopify 20-Day Rolling Volatility")
plt.xlabel("Date")
plt.ylabel("Volatility")
plt.xticks(rotation=45)
plt.show()

"""**Financial Summary Report**"""

mean_return = df["Daily_Return"].mean()
std_return = df["Daily_Return"].std()
max_return = df["Daily_Return"].max()
min_return = df["Daily_Return"].min()

print("Financial Summary Report")
print("------------------------")
print("Average Daily Return:", round(mean_return, 4))
print("Return Standard Deviation:", round(std_return, 4))
print("Highest Daily Return:", round(max_return, 4))
print("Lowest Daily Return:", round(min_return, 4))

print("\nStock Stability:")
if std_return < 0.02:
    print("The stock shows relatively stable returns.")
else:
    print("The stock shows higher return variability.")

print("\nHigh-Volatility Periods:")
high_volatility = df[df["Rolling_Volatility_20"] > df["Rolling_Volatility_20"].quantile(0.90)]

print(high_volatility[["Date", "Rolling_Volatility_20"]])