# -*- coding: utf-8 -*-
"""week_7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16q1P27PZZFfV-iLe1zVIa5oL7578IGB3
"""

import pandas as pd
import numpy as np

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/StudentsPerformance.csv")

categorical_columns = [
    "gender",
    "race/ethnicity",
    "parental level of education",
    "lunch",
    "test preparation course"
]

for column in categorical_columns:
    df[column] = df[column].str.strip()

subject_columns = [
    "math score",
    "reading score",
    "writing score"
]

for column in subject_columns:
    print("\n", column)
    print("Mean:", df[column].mean())
    print("Median:", df[column].median())
    print("Standard Deviation:", df[column].std())
    print("Q1:", df[column].quantile(0.25))
    print("Q2:", df[column].quantile(0.50))
    print("Q3:", df[column].quantile(0.75))

df["Total Marks"] = (
    df["math score"]
    + df["reading score"]
    + df["writing score"]
)

df["Percentage"] = (df["Total Marks"] / 300) * 100

print("\nTotal Marks and Percentage:")
print(df[["Total Marks", "Percentage"]].head())

print("\nExtreme Performance Outliers:")

for column in subject_columns:

    Q1 = df[column].quantile(0.25)
    Q3 = df[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_limit = Q1 - 1.5 * IQR
    upper_limit = Q3 + 1.5 * IQR

    outliers = df[
        (df[column] < lower_limit) |
        (df[column] > upper_limit)
    ]

    print("\n", column)
    print("Number of Outliers:", len(outliers))
    print(outliers[[column]].head())