# -*- coding: utf-8 -*-
"""week_5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BDjVLUA1a2oPp_euAyIjQ9wH5ZUUmXiw
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/healthcare_dataset.csv")

df.head()

df.info()

print("\nMissing Values:")
print(df.isnull().sum())

df.columns = df.columns.str.strip()

for column in df.select_dtypes(include='object').columns:
    df[column] = df[column].str.strip()

if 'Medical Code' in df.columns:
    df['Medical Code'] = df['Medical Code'].fillna('Unknown')

print("\nMissing Values After Cleaning:")
print(df.isnull().sum())

if 'Date of Admission' in df.columns:
    df['Date of Admission'] = pd.to_datetime(
        df['Date of Admission'],
        errors='coerce'
    )

if 'Discharge Date' in df.columns:
    df['Discharge Date'] = pd.to_datetime(
        df['Discharge Date'],
        errors='coerce'
    )

print("\nDate Data Types:")
print(df[['Date of Admission', 'Discharge Date']].dtypes)

if 'Date of Admission' in df.columns:
    df['Date of Admission'] = pd.to_datetime(
        df['Date of Admission'],
        errors='coerce'
    )

if 'Discharge Date' in df.columns:
    df['Discharge Date'] = pd.to_datetime(
        df['Discharge Date'],
        errors='coerce'
    )

df['Hospital Stay Days'] = ( df['Discharge Date'] - df['Date of Admission'] ).dt.days
print("\nHospital Stay Days:")
print(df[['Date of Admission', 'Discharge Date', 'Hospital Stay Days']].head())

df['Urgency Category'] = df['Admission Type'].replace({ 'Emergency': 'Emergency', 'Elective': 'Elective', 'Urgent': 'Urgent'})
print("\nUrgency Category:")
print(df[['Admission Type', 'Urgency Category']].head())

print("\nBilling Amount Statistics:")
print(df['Billing Amount'].describe())

print("\nHospital Stay Statistics:")
print(df['Hospital Stay Days'].describe())

demographic_summary = df.groupby( 'Medical Condition' ).agg({ 'Age': ['mean', 'min', 'max'], 'Billing Amount': 'mean', 'Hospital Stay Days': 'mean' })
print("\nDemographic Segmentation by Medical Condition:")
print(demographic_summary)