# -*- coding: utf-8 -*-
"""week_6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BefD6znDU9h-Xtkb32XQPsPozlddmOgt
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("/content/drive/MyDrive/CSV/healthcare_dataset.csv")

df.head()

print("Shape:", df.shape)

print("\nColumns:")
print(df.columns)

print("\nMissing Values:")
print(df.isnull().sum())

print("\nDataset Information:")
df.info()

df.dtypes

df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])

# Calculate Length of Stay
df["Stay Duration"] = (
    df["Discharge Date"] - df["Date of Admission"]
).dt.days

df[["Date of Admission", "Discharge Date", "Stay Duration"]].head()

# Convert dates
df["Date of Admission"] = pd.to_datetime(df["Date of Admission"])
df["Discharge Date"] = pd.to_datetime(df["Discharge Date"])

Billing = df.groupby(["Medical Condition","Insurance Provider"])["Billing Amount"].sum()
Billing

data = df.groupby(
    ["Medical Condition", "Insurance Provider"]
)["Billing Amount"].mean().unstack()

# Bar chart
data.plot(
    kind="bar",
    stacked=True,
    figsize=(12, 6)
)

plt.title("Average Billing Amount by Medical Condition and Insurance Provider")
plt.xlabel("Medical Condition")
plt.ylabel("Average Billing Amount")
plt.xticks(rotation=45)
plt.legend(title="Insurance Provider")

plt.tight_layout()
plt.show()

plt.figure(figsize=(12,6))

sns.violinplot(
    data=df,
    x="Medical Condition",
    y="Billing Amount"
)

plt.title("Billing Amount Distribution by Medical Condition")
plt.xlabel("Medical Condition")
plt.ylabel("Billing Amount")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,6))

sns.violinplot(
    data=df,
    x="Insurance Provider",
    y="Billing Amount"
)

plt.title("Billing Amount Distribution by Insurance Provider")
plt.xlabel("Insurance Provider")
plt.ylabel("Billing Amount")
plt.xticks(rotation=45)
plt.tight_layout()
plt.show()

plt.figure(figsize=(12,6))
df['Admission_Month'] = df['Date of Admission'].dt.to_period('M')
Monthly_Admission = df.groupby('Admission_Month').size()
Monthly_Admission.plot(kind="line",marker="o")

plt.title("Monthly Patient Admission")
plt.xlabel("Month")
plt.ylabel("Number of Admissions")
plt.xticks(rotation=45)
plt.grid()

corelation_matrix=df[["Age","Stay Duration","Billing Amount"]].corr()
corelation_matrix

sns.heatmap(corelation_matrix,annot=True,cmap="coolwarm")
plt.title("Correlation Heatmap")
plt.show()